<?php

/**
 * @file
 * Mailchimp rules module
 */

/**
 * Returns a new instance of an MailChimp API class.
 *
 * @param string $class_name
 *   The class name you want an instance from.
 * @param string $api_key
 *   The MailChimp api key to use if not the default, which is retrieved from
 *   the variable mailchimp_api_key.
 *
 * @return object||null
 *   Either an instance of an MailChimp API class or NULL, if the library is
 *   missing or could not be loaded.
 */
function mailchimp_rules_get_api_object($class_name = 'Mailchimp', $api_key = NULL) {
  $class_name = 'Mailchimp\\' . $class_name;

  // todo: allow the mailchimp library to be installed via libraries.

  // Check if the composer autoload file loaded the mailchimp library.
  if (!class_exists($class_name)) {

    $msg = 'Failed to load MailChimp PHP library. Please refer to the installation requirements.';
    watchdog('mailchimp_rules', $msg, array(), WATCHDOG_ERROR);
    drupal_set_message(t($msg), 'error', FALSE);

    return NULL;
  }

  if (!$api_key) {
    $api_key = variable_get('mailchimp_api_key');
  }

  if (empty($api_key)) {
    $msg = 'Please set an API key for the MailChimp integration.';
    watchdog('mailchimp_rules', $msg, array(), WATCHDOG_ERROR);
    drupal_set_message(t($msg), 'error', FALSE);
  }

  // Set the timeout to something that won't take down the Drupal site:
  $timeout = 60;

  return new $class_name($api_key, 'apikey', $timeout);
}

/**
 * Retrieves the lists for the set API key.
 *
 * @return array
 *   A list of MailChimp lists with the id as key and name as value.
 */
function mailchimp_rules_retrieve_lists() {
  $lists_api = mailchimp_rules_get_api_object('MailchimpLists');

  $lists = array();
  try {
    // Only get the first 500 for now.
    $res = $lists_api->getLists(array('count' => 500));

    foreach ($res->lists as $list) {
      $lists[$list->id] = $list->name;
    }
  }
  catch (MailchimpAPIException $exception) {
    $msg = 'Could not retrieve the mailchimp lists.';
    watchdog('mailchimp_rules', $msg, array(), WATCHDOG_ERROR);
    drupal_set_message(t($msg), 'error', FALSE);
  }

  return $lists;
}
